name: openmm
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - openmm
  - cudatoolkit
  - git
  - jupyterlab
  - numpy
  - pandas
  - scipy
  - matplotlib
  - ipywidgets
  - ipympl
  - rdkit
  - openbabel
  - mdtraj
  - nglview
  - pymbar
  - pdbfixer
  - parmed
  - jax
  - ruff
  - pre-commit
  - jupyterlab-git
  - python-lsp-ruff
  - jupyterlab-lsp
  - jedi-language-server
  - jupyter-resource-usage
  - pip:
    - jupyterlab-code-formatter
